pixelgrew:
  title: "👋 Welcome to PixelGrew!"
  description: |
    Hello, adventurer! ✨
    Thanks for stopping by. This is your official greeting from the PixelGrew community.
    Whether you're here to play, build, create, or just hang out, you're in the right place.
    Check out the website and join the fun!
  website: "https://pixelgrew.com"
  shoutout: "Say hi to someone new today and share the PixelGrew vibe!"
  fun_fact: "PixelGrew is powered by the creativity of players like YOU."
  next_steps:
    - "1. Visit our site"
    - "2. Join the community"
    - "3. Make something awesome"
    - "4. Say hello to someone in chat!"

  message_of_the_day: "Hello! We're glad you found us. pixelgrew.com"
